# This script runs the scripts generated by Run Jin to convert table outputs to visualizations

# sample of interest
pnoc008_sample_of_interest <- sampleInfo$subjectID

# directories
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
source(file.path(root_dir, "code", "utils", "define_directories.R"))

# pathway enrichment pediatric
cmd <- paste("Rscript", file.path(code_dir, "graph-updates", "01-pathway_enrichment_pediatric.R"), "--patient", pnoc008_sample_of_interest)
system(cmd)

# mutational analysis pediatric
cmd <- paste("Rscript", file.path(code_dir, "graph-updates", "02-mutational_analysis_maf_cnv_pediatric.R"), "--patient", pnoc008_sample_of_interest)
system(cmd)

# pathway enrichment adult
cmd <- paste("Rscript", file.path(code_dir, "graph-updates", "03-pathway_enrichment_adult.R"), "--patient", pnoc008_sample_of_interest)
system(cmd)

# mutational analysis adult
cmd <- paste("Rscript", file.path(code_dir, "graph-updates", "04-mutational_analysis_maf_cnv_adult.R"), "--patient", pnoc008_sample_of_interest)
system(cmd)

