# This script runs the scripts generated by Run Jin to convert table outputs to visualizations
# directories
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
module_dir <- file.path(root_dir, "code", "tables_to_plots")
output_dir <- file.path(patient_dir, "output", "transcriptomically_similar_analysis")
dir.create(output_dir, showWarnings = F, recursive = T)

# pathway enrichment pediatric
cmd <- paste("Rscript", file.path(module_dir, "01-pathway_enrichment_pediatric.R"), 
             "--patient", patient,
             "--output_dir", output_dir)
system(cmd)

# mutational analysis pediatric
cmd <- paste("Rscript", file.path(module_dir, "02-mutational_analysis_maf_cnv_pediatric.R"), 
             "--patient", patient,
             "--output_dir", output_dir)
system(cmd)

# pathway enrichment adult
cmd <- paste("Rscript", file.path(module_dir, "03-pathway_enrichment_adult.R"), 
             "--patient", patient,
             "--output_dir", output_dir)
system(cmd)

# mutational analysis adult
cmd <- paste("Rscript", file.path(module_dir, "04-mutational_analysis_maf_cnv_adult.R"), 
             "--patient", patient,
             "--output_dir", output_dir)
system(cmd)

