########################
# All requisite packages
########################

BiocManager::install("ComplexHeatmap")
BiocManager::install("DT")
BiocManager::install("GSEABase")
BiocManager::install("GSVA")
BiocManager::install("GeneNetworkBuilder")
BiocManager::install("GenomicRanges")
BiocManager::install("RCircos")
BiocManager::install("RColorBrewer")
devtools::install_github("d3b-center/RDiseaseXpress")
BiocManager::install("RTCGA.clinical")
BiocManager::install("Rtsne")
BiocManager::install("biomaRt")
BiocManager::install("circlize")
BiocManager::install("copynumber")
BiocManager::install("data.table")
BiocManager::install("decompTumor2Sig")
BiocManager::install("doMC")
BiocManager::install("dplyr")
BiocManager::install("edgeR")
BiocManager::install("flexdashboard")
BiocManager::install("ggnetwork")
BiocManager::install("ggthemes")
BiocManager::install("grid")
BiocManager::install("igraph")
BiocManager::install("kableExtra")
BiocManager::install("knitr")
BiocManager::install("limma")
BiocManager::install("msigdbr")
BiocManager::install("network")
BiocManager::install("optparse")
BiocManager::install("plotly")
BiocManager::install("preprocessCore")
BiocManager::install("randomcoloR")
BiocManager::install("readxl")
BiocManager::install("reshape2")
BiocManager::install("scales")
BiocManager::install("sna")
BiocManager::install("stringr")
BiocManager::install("survival")
BiocManager::install("survminer")
BiocManager::install("sva")
BiocManager::install("tidyverse")
remotes::install_github("jlmelville/uwot")
devtools::install_github('dviraran/xCell')
BiocManager::install("xlsx")

# double check these
BiocManager::install("BSgenome.Hsapiens.UCSC.hg38")
BiocManager::install("R.utils")
BiocManager::install("TxDb.Hsapiens.UCSC.hg38.knownGene")
BiocManager::install("intergraph")
BiocManager::install("rtracklayer") 

