---
title: "Pathway Analysis Pediatric Graph Conversion"
author: "Run Jin"
date: "8/23/2021"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
```

Define directory
```{r define directory, include=FALSE}
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
data_dir <- file.path(root_dir, "data")

pediatric_dir <- file.path(root_dir, "graph-updates/plots/pediatric")
if (!dir.exists(pediatric_dir )) {
  dir.create(pediatric_dir , recursive = TRUE)
}

plot_dir <- file.path(pediatric_dir, "pathway_barplot")
if (!dir.exists(plot_dir )) {
  dir.create(plot_dir , recursive = TRUE)
}
```

## P5 pathway enrichment
### Read in the files and arrange for plotting
```{r read in for pathway enrichment}
pathway_analysis_pediatric <- readRDS(file.path(data_dir,"pathway_analysis_pediatric.rds"))
shared_pathway_pediatric <- pathway_analysis_pediatric$shared_pathways %>%
  filter(sample_name == "PNOC008-36")

shared_pathway_pediatric$padj <- as.numeric(shared_pathway_pediatric$padj) 
shared_pathway_pediatric$direction <- factor(shared_pathway_pediatric$direction, levels = c("up", "down"))
shared_pathway_pediatric <- shared_pathway_pediatric %>% arrange(padj) %>% arrange(direction)

shared_pathway_pediatric$pathway <- factor(shared_pathway_pediatric$pathway, levels = unique(shared_pathway_pediatric$pathway))
```

### Plot for pathway enrichment
```{r plot pathway enrichment}

ggplot(shared_pathway_pediatric, aes(pathway, y = (-1)*log10(padj), fill = direction)) + 
    geom_bar(stat="identity") + coord_flip() + theme_bw() +
    xlab("") + 
    ylab("-log10 Adj. P-Value") + 
    theme(plot.margin = unit(c(1, 5, 1, 7), "cm")) + 
    scale_fill_manual(name = "Direction", values = c("down" = "forest green", "up" = "red")) + 
    ggtitle(paste0("Comparison against pediatric")) 

ggsave(file.path(plot_dir, "pathway_analysis_pediatric.png"), height = 6, width = 15)
```   
